/********************************************************************
 *  api_server.js
 *  ‑ Reads ratings.json generated by build_ratings.js
 *  ‑ Exposes GET /trueskill/{team}
 *  (No RobotEvents token needed)
 *******************************************************************/
import fs from 'node:fs/promises';
import express from 'express';

const app  = express();
const port = 3000;

let data;
try {
  const raw = await fs.readFile('ratings.json','utf8');
  data = JSON.parse(raw);
  console.log(`Loaded ratings for ${Object.keys(data.teams).length} teams`);
} catch (e) {
  console.error('Failed to read ratings.json – run build_ratings.js first');
  process.exit(1);
}

app.get('/trueskill/:teamNumber', (req,res) => {
  const team = req.params.teamNumber.toUpperCase();
  const r    = data.teams[team];
  if (!r) return res.status(404).json({ error:'No rating for that team' });
  res.json({ team, ...r, conservative: r.trueskill.toFixed(2) });
});

app.listen(port, () =>
  console.log(`TrueSkill API ready on http://localhost:${port}`));
